package com.libs.vo {
	import flash.display.Sprite;
	import flash.events.Event;
	import flash.display.Shape;
	
	public class ImagesVO {
		public static const SWFOBJECT:String = "so";
		
		public function ImagesVO() {
		}
		
		public static function setGlobal(name:String,value:*):void {
			GlobalsVO.setGlobal(name,value);
		}
		
		public static function getGlobal(name:String):* {
			return GlobalsVO.getGlobal(name);
		}
		
		public static function getAsset(name:String):Sprite {
			try {
				var c:Class = GlobalsVO.getGlobal(SWFOBJECT).target.applicationDomain.getDefinition(name) as Class;
				return new c() as Sprite;
			} catch(e:Error) {
				trace("m: "+e.toString()+'\n'+e.getStackTrace());
			}
			var s:Sprite = new Sprite();
			s.addChild(missingImage());
			s.width = 12;
			s.height = 14;
			return s;
		}
		
		/**
		* Create Asset0 DisplayObject.
		* Generated by µSprite version 0.6.5.
		* @return a Shape object
		*/
		
		private static function missingImage():Shape {
		    // Coordinate system: (0, 0) - (300, 300).
		    var newAsset0:Shape = new Shape();
		    var g:* = newAsset0.graphics;
		    newAsset0.name = "Asset0." + newAsset0.name;
		    g.lineStyle(1);
		    g.moveTo(38.40, 32.40);
		    g.beginFill(0xF40202);
		    g.moveTo(1.20, 1.20);
		    g.curveTo(90.80, 1, 219.60, 0.80);
		    g.lineTo(299.20, 80.40);
		    g.lineTo(299.20, 139.20);
		    g.lineTo(280.80, 99.20);
		    g.lineTo(260, 139.20);
		    g.lineTo(239.60, 99.60);
		    g.lineTo(220, 139.20);
		    g.lineTo(200, 100);
		    g.lineTo(180, 139.60);
		    g.lineTo(160, 99.60);
		    g.lineTo(138.80, 139.60);
		    g.lineTo(121.20, 98.80);
		    g.lineTo(100, 139.60);
		    g.lineTo(79.20, 100);
		    g.lineTo(60, 140);
		    g.lineTo(40.40, 99.60);
		    g.lineTo(19.60, 139.20);
		    g.lineTo(0.80, 99.60);
		    g.curveTo(0.80, 51.60, 0.80, 1.60);
		    g.moveTo(218.40, 0.40);
		    g.curveTo(218, 41.80, 218, 80.80);
		    g.curveTo(251, 81.80, 300, 81.20);
		    g.moveTo(298.80, 219.20);
		    g.lineTo(280.40, 180);
		    g.lineTo(259.20, 218.80);
		    g.lineTo(239.20, 179.60);
		    g.lineTo(218.80, 218.40);
		    g.lineTo(199.60, 179.20);
		    g.lineTo(180, 219.20);
		    g.lineTo(160.40, 179.60);
		    g.lineTo(139.20, 220);
		    g.lineTo(120, 179.60);
		    g.lineTo(99.60, 218.80);
		    g.lineTo(80.80, 180);
		    g.lineTo(59.60, 219.20);
		    g.lineTo(39.60, 180);
		    g.lineTo(20, 219.60);
		    g.lineTo(0.40, 180);
		    g.lineTo(0.80, 299.20);
		    g.lineTo(299.20, 298.40);
		    g.endFill();
		    return newAsset0;
		}
	}
}